# Generated by Django 2.0.2 on 2018-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180220_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='priority',
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
