# Generated by Django 2.0.2 on 2018-03-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180303_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
