# Generated by Django 2.0.2 on 2018-03-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180307_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at', 'tag']},
        ),
    ]
