# Generated by Django 2.0.2 on 2018-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180307_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, default='general', max_length=20, null=True),
        ),
    ]
