# Generated by Django 2.0.2 on 2018-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180307_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
